### ISSUE TITLE
Module-2 Review

### ISSUE THREAD

**Issue by amalik99** [SpektraSystems/Azure-PostgreSQL-DMS-Lab#2]
1. pg_dump -o -h localhost -U postgres -d dvdrental -s  > dvdrentalSchema.sql . Store this in C:\DMS\dvdrentalSchema.sql

2. --service-name PostgresCLI  >> is wrong in commands. ask them to enter it in all commands

3.az dms project task show --service-name PostgresCLI --project-name PGMigration --resource-group PostgresDemo --name Runnowtask >> command needs to be modified to allow user to enter their values

4. az dms project task cutover --service-name <dms name> --project-name <project name> --resource-group <cloudrg name> --name <task name>  --database-name Inventory >> database name needs to be dvdrental. not inventory

**Comment by GhumanNavneet** [comment]
completed from my side
